#!/usr/bin/env python3
"""Recover Win16 API ordinal -> name mappings from OMF import libraries.

The engine calls KERNEL, USER, GDI and MMSYSTEM entirely by ordinal, so a raw
call map shows KERNEL.102 rather than GlobalAlloc. The import libraries shipped
with the period SDK carry the mapping in OMF IMPDEF records, which makes this
authoritative rather than a table typed out from memory.

IMPDEF lives inside a COMENT record:

  88            COMENT record type
  <len:u16>     record length
  <attr:u8>     comment attributes
  A0            class: OMF extension
  01            subtype: IMPDEF
  <ordflag:u8>  0 = import by name, non-zero = import by ordinal
  <pstr>        internal name
  <pstr>        module name
  if ordflag:   <ordinal:u16>
  else:         <pstr> exported name (empty means same as internal)

Usage:  libw_names.py LIBW.LIB [more.lib ...]
"""
import struct
import sys
from pathlib import Path


def pstr(d, p):
    n = d[p]
    return d[p + 1:p + 1 + n].decode("ascii", "replace"), p + 1 + n


def impdefs(path):
    """Scan for IMPDEF COMENT records.

    A sequential record walk does not survive an OMF *library*: modules are
    padded to page boundaries, so the stream is not contiguous. Scanning for the
    record signature and validating each hit is robust to that padding.
    """
    d = Path(path).read_bytes()
    out = {}
    i = 0
    while True:
        i = d.find(b"\x88", i)
        if i < 0 or i + 6 > len(d):
            break
        rlen = struct.unpack_from("<H", d, i + 1)[0]
        if not (5 <= rlen <= 512) or i + 3 + rlen > len(d):
            i += 1
            continue
        if d[i + 4] != 0xA0 or d[i + 5] != 0x01:
            i += 1
            continue
        try:
            q = i + 6
            ordflag = d[q]; q += 1
            internal, q = pstr(d, q)
            module, q = pstr(d, q)
            if ordflag and q + 2 <= len(d):
                ordinal = struct.unpack_from("<H", d, q)[0]
                if internal and module and 0 < ordinal < 65535:
                    out.setdefault(module.upper(), {})[ordinal] = internal
        except (IndexError, UnicodeDecodeError):
            pass
        i += 3 + rlen
    return out


def main():
    merged = {}
    for path in sys.argv[1:]:
        for mod, m in impdefs(path).items():
            merged.setdefault(mod, {}).update(m)
    for mod in sorted(merged):
        print("%s: %d ordinals" % (mod, len(merged[mod])))
    # emit a python table for ne_callmap to import
    outp = Path(__file__).resolve().parent / "win16_ordinals.py"
    with outp.open("w") as f:
        f.write("# Generated by libw_names.py from period import libraries.\n")
        f.write("ORDINALS = {\n")
        for mod in sorted(merged):
            f.write("  %r: {\n" % mod)
            for o in sorted(merged[mod]):
                f.write("    %d: %r,\n" % (o, merged[mod][o]))
            f.write("  },\n")
        f.write("}\n")
    print("wrote", outp)


if __name__ == "__main__":
    main()
