#!/usr/bin/env python3
"""Annotate every imported call site in a module with a resolved symbol name.

ne_imports.py gives MODULE.ordinal. This resolves the ordinal to a name by
reading the exporting DLL's resident and non-resident name tables, so calls into
JUNGR01 come back as RESLOADRESOURCE rather than JUNGR01.11.

The other three engine DLLs shipped with their export names stripped to
S_0nn / U_0nn / A_0nn, so those stay numeric -- that is the real state of the
binary, not a gap in this tool.

Usage:  ne_callmap.py MODULE.EXE [--seg N]
"""
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from ne_imports import parse
try:
    from win16_ordinals import ORDINALS as WIN16
except ImportError:                      # generated by libw_names.py
    WIN16 = {}

ROOT = Path(__file__).resolve().parent.parent
BINDIR = ROOT / "orig" / "cd" / "JUNGLE"


def export_names(path):
    d = Path(path).read_bytes()
    ne = struct.unpack_from("<H", d, 0x3C)[0]
    cbnres = struct.unpack_from("<H", d, ne + 0x20)[0]
    restab = struct.unpack_from("<H", d, ne + 0x26)[0]
    nrestab = struct.unpack_from("<I", d, ne + 0x2C)[0]
    out = {}
    for base, limit, resident in ((ne + restab, None, True), (nrestab, cbnres, False)):
        p, end, first = base, base + (limit if limit else 4096), True
        while p < end:
            n = d[p]
            if n == 0:
                break
            nm = d[p + 1:p + 1 + n].decode("ascii", "replace")
            p += 1 + n
            ordv = struct.unpack_from("<H", d, p)[0]
            p += 2
            if not first or not resident:
                out[ordv] = nm
            first = False
    return out


def chains(seg, body):
    """Walk relocation chains: each record heads a list, 0xFFFF ends it."""
    resolved = {}
    for r in seg["relocs"]:
        if r["rel_type"] not in ("ORDINAL", "NAME"):
            continue
        off, seen = r["offset"], set()
        while off != 0xFFFF and off + 2 <= len(body) and off not in seen:
            seen.add(off)
            resolved[off] = r
            off = struct.unpack_from("<H", body, off)[0]
    return resolved


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else str(BINDIR / "JUNGLE.EXE")
    want = [a.split("=", 1)[1] for a in sys.argv[1:] if a.startswith("--seg=")]
    img = parse(path)
    data = Path(path).read_bytes()

    tables = {}
    for m in img["modules"]:
        cand = BINDIR / (m + ".DLL")
        if cand.exists():
            tables[m] = export_names(cand)

    total = 0
    named = 0
    for seg in img["segs"]:
        if want and str(seg["i"]) not in want:
            continue
        body = data[seg["off"]:seg["off"] + seg["len"]]
        resolved = chains(seg, body)
        if not resolved:
            continue
        print("=== %s segment %d — %d imported call sites" % (Path(path).name, seg["i"], len(resolved)))
        for off in sorted(resolved):
            r = resolved[off]
            mod = r.get("module", "")
            nm = tables.get(mod, {}).get(r.get("ordinal", -1))
            if not nm:
                nm = WIN16.get(mod.upper(), {}).get(r.get("ordinal", -1))
            total += 1
            if nm and not nm.startswith(("S_", "U_", "A_")):
                named += 1
            print("  seg%d:%04x  %-16s %s" % (seg["i"], off, r["symbol"], nm or ""))
    print("\n%d call sites, %d resolved to a meaningful name (%.0f%%)"
          % (total, named, 100.0 * named / total if total else 0))


if __name__ == "__main__":
    main()
